# Render blueprint for the backend API
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: food-delivery-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # Set your Node version (optional but recommended)
      - key: NODE_VERSION
        value: 18
      # Set these in the Render Dashboard after creating the service
      # - key: MONGO_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: STRIPE_WEBHOOK_SECRET
      #   sync: false
